# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
    - "3.6"

cache:
    pip: true

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # TODO: Use 'travis encrypt --com -r adafruit/<repo slug>' to generate
  #       the encrypted password for adafruit-travis. Paste result below.
  - provider: pypi
    user: adafruit-travis
    password:
      secure: g8Ni3zefHq0vE3vsyBAxz5bqceF8jo829FcaBSoYDw4hqN46VZdJReRbBsktc/LcnrjDcYxLLFAQ6MpH+v0VpTko3ySeJoLIvrAPk81FYj+OfLnkRuL43uhYwtemMPK2Ggo6d73Rz0QEdnvGLYZ3wXRsYU6l8AU3OjBG1+CS03R87yRae/gMCYSoxskwcX0y+UHmk4Sgyors2y5Jkbn91jiPb/hOgtstI0Z7OJyH7UdCJ7CnxnDfp3ONdjHmVUHygQ+ZpH+9fNXvbZiRbHYh7e0rBRcabi7C78v/KsfeO/R19DjB76aOxld5guim7dGOW59TAI64aQA+M3jjxwgegUtdOdX5wu+HqvUUOe5iKCF1FSJRP69xL1EinlIExOQ94SLG1GBPgXhavFbFI9BxCieIMNoJBUQYMkjvFK3rePXS3bzfEVyUFfTTq0D7mog0y3FBR34jTWxRVlD2O2WT5gMZtOqkrzHgDasx/E4j8TP4J07o4oRs65Lat5qUBdlO6PzMFmaP9NgbryayOcycoNL3TMzmJghOV0o6H/07dUhHH1Qswy6Na77EHffrwOV9yRkNWa87qTkLWXXj984l6Yla0gpwKVFXnlamjw1tJ/rxW8WQ7bmCXBGw1zT+fW6ZSJvj3VHvglXWV8IZN3VBDN/4g3MwSlFLWKxKcxlKacM=
    on:
      tags: true

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint adafruit_testrepo.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-testrepo --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
